/** For Mozzi-internal use: Apply hardware specific config defaults and config checks: AVR */

// Step 1: Apply missing defaults
// NOTE: This step is actually required for all ports

#if not defined(MOZZI_AUDIO_MODE)
#define MOZZI_AUDIO_MODE MOZZI_OUTPUT_PWM
#endif

#if not defined(MOZZI_AUDIO_RATE)
#define MOZZI_AUDIO_RATE 16384
#endif

#if not defined(MOZZI_ANALOG_READ)
#define MOZZI_ANALOG_READ MOZZI_ANALOG_READ_STANDARD
#endif

// Pins for regular PWM output
#if MOZZI_IS(MOZZI_AUDIO_MODE, MOZZI_OUTPUT_PWM)
#  if !defined(MOZZI_AUDIO_PIN_1)
#define MOZZI_AUDIO_PIN_1 TIMER1_A_PIN
#define MOZZI_AUDIO_PIN_1_REGISTER OCR1A
#  endif
#  if (MOZZI_AUDIO_CHANNELS > 1) && !defined(MOZZI_AUDIO_PIN_2)
#define MOZZI_AUDIO_PIN_2 TIMER1_B_PIN
#define MOZZI_AUDIO_PIN_2_REGISTER OCR1B
#  endif

#  if !defined(MOZZI_PWM_RATE)
#define MOZZI_PWM_RATE 32768
#  endif

#define MOZZI_AUDIO_BITS 8
#define MOZZI_AUDIO_BITS_OPTIMISTIC 9
#define MOZZI_AUDIO_BIAS ((uint8_t) 244)
#endif

// Pins for 2 pin HIFI PWM output
#if MOZZI_IS(MOZZI_AUDIO_MODE, MOZZI_OUTPUT_2PIN_PWM)
#  if !defined(MOZZI_AUDIO_PIN_1)
#define MOZZI_AUDIO_PIN_1 TIMER1_A_PIN
#define MOZZI_AUDIO_PIN_1_REGISTER OCR1A
#  endif
#  if !defined(MOZZI_AUDIO_PIN_1)
#define MOZZI_AUDIO_PIN_1_LOW TIMER1_B_PIN
#define MOZZI_AUDIO_PIN_1_LOW_REGISTER OCR1B
#  endif

#  if !defined(MOZZI_PWM_RATE)
#define MOZZI_PWM_RATE 125000
#  endif

#  if !defined(MOZZI_PWM_RATE)
#define MOZZI_AUDIO_BITS_PER_CHANNEL 7
#  endif

#define MOZZI_AUDIO_BITS (2*MOZZI_AUDIO_BITS_PER_CHANNEL)
#endif

// Step 2: Check
// NOTE: This step is not technically required, but a good idea in any port

MOZZI_CHECK_SUPPORTED(MOZZI_AUDIO_MODE, MOZZI_OUTPUT_PWM, MOZZI_OUTPUT_2PIN_PWM, MOZZI_OUTPUT_EXTERNAL_TIMED, MOZZI_OUTPUT_EXTERNAL_CUSTOM)

#if MOZZI_IS(MOZZI_AUDIO_MODE, MOZZI_OUTPUT_PWM)
MOZZI_CHECK_SUPPORTED(MOZZI_AUDIO_CHANNELS, MOZZI_MONO, MOZZI_STEREO)
#endif
#if MOZZI_IS(MOZZI_AUDIO_MODE, MOZZI_OUTPUT_2PIN_PWM)
MOZZI_CHECK_SUPPORTED(MOZZI_AUDIO_CHANNELS, MOZZI_MONO)
#endif

/** should we enforce the following?
#if (MOZZI_IS(MOZZI_AUDIO_MODE, MOZZI_OUTPUT_PWM) || MOZZI_IS(MOZZI_AUDIO_MODE, MOZZI_OUTPUT_2PIN_PWM))
MOZZI_CHECK_SUPPORTED(MOZZI_AUDIO_RATE, 16384, 32768)
#endif */

MOZZI_CHECK_SUPPORTED(MOZZI_ANALOG_READ, MOZZI_ANALOG_READ_NONE, MOZZI_ANALOG_READ_STANDARD)
MOZZI_CHECK_SUPPORTED(MOZZI_AUDIO_INPUT, MOZZI_AUDIO_INPUT_NONE, MOZZI_AUDIO_INPUT_STANDARD)
#include "../config/known_16bit_timers.h"
#if defined(TIMER1_C_PIN)
MOZZI_CHECK_SUPPORTED(MOZZI_AUDIO_PIN_1, TIMER1_A_PIN, TIMER1_B_PIN, TIMER1_C_PIN);
#else
MOZZI_CHECK_SUPPORTED(MOZZI_AUDIO_PIN_1, TIMER1_A_PIN, TIMER1_B_PIN);
#endif

